### ISSUE TITLE
Link over graphic thumbnail leads to broken page

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsabs#223]
The link we create when somebody clicks on the thumbnail in an abstract page is missing a trailing "/" and as such generates an error page.  Example:
http://adslabs.org/adsabs/abs/2013ApJ...779L..12S/
The link on the right hand bar is:
http://adslabs.org/adsabs/abs/2013ApJ...779L..12S/graphics
but should instead be:
http://adslabs.org/adsabs/abs/2013ApJ...779L..12S/graphics/

**Comment by ehenneken** [comment]
Trailing slash implemented
